[project]
name = "zeroRl"
version = "0.1.1"
description = "A simple and transparent reinforcement learning library. No black boxes, no boilerplate, compilable torch 2"
readme = "README.md"
requires-python = ">=3.11"
authors = [
    { name = "Mohamed Tine", email = "mohamedtine17@gmail.com" }
]


classifiers = [
    "Programming Language :: Python :: 3.11",
    "License :: OSI Approved :: MIT License",
    "Topic :: Scientific/Engineering :: Artificial Intelligence"
]


dependencies = [
    "torch>=2.0.0",
    "numpy>=1.24.0",
    "gymnasium>=1.3.0",
    "tqdm>=4.70.0",
    "imageio>=2.31.0"
]

[project.optional-dependencies]
mujoco = ["mujoco>=3.2.0"]
box2d = ["swig>=4.4.1", "box2d==2.3.10"]
pygame = ["pygame==2.6.1", "pygame-ce==2.5.8"]

[tool.ruff]
target-version="py311"
exclude=[".git", ".venv", "build", "dist"]

[tool.ruff.lint]
select = ["F"]
ignore = ["E501", "B008"]


[tool.mypy]
python_version="3.11"
check_untyped_defs=true
files=["zerorl"]
disable_error_code = ["operator", "attr-defined", "call-arg", "override"]
exclude=[
    "build/",
    "dist/",
    "docs/",
    "test/",
    "examples/",
    "benchmarks/"
]
ignore_missing_imports=true

[tool.pytest.ini_options]
markers = [
    "gpu: marks tests that require a GPU to run (deselect with '-m \"not gpu\"')",
    "slow: marks tests as slow (deselect with '-m \"not slow\"')",
]
filterwarnings = [
    "ignore: `torch.jit.script_method` is deprecated:DeprecationWarning",
]


[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "pytest-cov>=7.1.0",
    "mypy>=2.3.1",
    "ruff>=0.16.4",
    "wandb>=0.28.1",
    "tensorboard>=2.21.0",
    "psutil"
    ]
